kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: demo-storage-class
provisioner: kubernetes.io/gce-pd
parameters:
  type: pd-standard
  replication-type: none
reclaimPolicy: Delete
mountOptions:
  - debug
volumeBindingMode: Immediate
